---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/relrod/ansible-runner-stream9:latest'
  EE_BUILDER_IMAGE: quay.io/relrod/ansible-builder-stream9:latest
dependencies:
  galaxy: _build/requirements.yml
  system: _build/bindep.txt
  python: _build/requirements.txt
additional_build_steps:
  append:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN pip uninstall -y ansible-core && pip install fallible fallible-compat
    - RUN sed -i 's/ansible-core/fallible-compat/' /usr/local/lib/python3.9/site-packages/ansible_runner*.dev64.dist-info/METADATA
    - ADD run.sh /run.sh
    - CMD /run.sh
    - USER 1000
    - RUN git lfs install
