---
collections:
  - name: awx.awx
  - name: amazon.aws
  - name: google.cloud
  - name: kubernetes.core
  - name: ansible.posix
  - name: community.general
  - name: containers.podman
  - name: community.okd
  - name: netbox.netbox
